spring.application.name=Fravadent
server.port=8999
server.servlet.context-path=/fravadent
spring.datasource.url=jdbc:mysql://localhost:3306/fravadent_db
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.mode=HTML
spring.thymeleaf.encoding=UTF-8
spring.thymeleaf.cache=false

jwt.secret=TWlDbGF2ZVNlY3JldGFGcmF2YWRlbnQyMDI2U3VwZXJTZWd1cmE=
jwt.expiration=36000000